platform :ios, '8.0'

target 'BWTesting' do

	pod 'Masonry'

  target 'BWTestingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BWTestingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
